version: '3'

services:
  app:
    image: ghcr.io/sbroekhoven/unshortened:latest
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - SITE_TITLE=${SITE_TITLE:-Unshortened}
      - NAMESERVER=${NAMESERVER:-1.1.1.1}
      - SITE_URL=${SITE_URL:-}
      - PORT=8080
    volumes: []
    restart: unless-stopped